name: 'Ansible Builder Action'
description: 'Ansible Builder Github Action'
branding:
  icon: 'book-open'
  color: 'white'
inputs:
  action:
    default: create
    description: Ansible builder action create or build
    required: true
    type: string
  args:
    default: ''
    description: action arguments
    required: false
    type: string
  python-version:
    default: '3.12'
    description: Python version
    required: false
    type: string
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '${{ inputs.python-version }}'
    - name: Create and start virtual environment
      shell: bash
      run: |
        python3 -m venv builder-venv
        source builder-venv/bin/activate
        echo "${{ github.action_path }}" >> $GITHUB_PATH
        pip install --upgrade pip
    - name: Install ansible-builder
      shell: bash
      run: |
        pip install setuptools ansible-builder==3.0.0
    - name: Run ansible-builder
      shell: bash
      run: |
        ansible-builder ${{ inputs.action }} ${{ inputs.args }}
